### ISSUE TITLE
$model on catalog/_product

### ISSUE THREAD

**Issue by inthinks** [samdark/yii2-shop#18]
where does $model come from?
can you explain to me please?
What techniques do you use ?
it suddenly appearing an instance object of Product.

thanks.

**Comment by samdark** [comment]
https://github.com/samdark/yii2-shop/blob/master/frontend/views/catalog/list.php#L24
https://github.com/samdark/yii2-shop/blob/master/frontend/controllers/CatalogController.php#L35
