### ISSUE TITLE
"Permission denied" error message from github

### ISSUE THREAD

**Issue by ThinkALot** [samdark/yii2-shop#19]
When I run this:
git clone git@github.com:samdark/yii2-shop.git

I get the following message:
Cloning into 'yii2-shop'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

What am I doing wrong?

Thanks.

**Comment by samdark** [comment]
https://help.github.com/search/?utf8=✓&q=Permission+denied

**Comment by ThinkALot** [comment]
Thanks.
For anyone else who gets stuck -- if you're on windows: I found Git Bash easier to troubleshoot than Putty. The instructions are here:
https://help.github.com/articles/generating-ssh-keys/
