### ISSUE TITLE
How can I register a user name and password the first time? 

### ISSUE THREAD

**Issue by ThinkALot** [samdark/yii2-shop#20]
After installing the app, I can see the frontend and backend and the login page, but how can I register a user name and password the first time? I can't see any place to do that. 

For example, the login page is here:
http://admin.yii2shop.local/index.php?r=site%2Flogin
but to use that, I need an _existing_ Username and Password. 

So how can I register the first time?

**Comment by samdark** [comment]
You can do it via frontend signup form.

**Comment by ThinkALot** [comment]
Thanks. 
For anyone else who gets stuck, there's no link, but it's here (I guessed):
index.php?r=site%2Fsignup

**Comment by MaxFlower** [comment]
Линка на форму нет, но тоже догадался найти через index.php?r=site%2Fsignup
