### ISSUE TITLE
please update readme.md

### ISSUE THREAD

**Issue by songwutk** [samdark/yii2-shop#24]
I followed your instruction that not successful.

C:\xampp\htdocs>git clone git@github.com:samdark/yii2-shop.git myshop
Cloning into 'myshop'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Next I clone project instead.

=> git clone https://github.com/samdark/yii2-shop.git
OK

=>composer global require "fxp/composer-asset-plugin:~1.0.3"
OK

=> cd yii2 shop
=> composer install
OK

=> init  
(Dev mode & edit db config)

=> yii migrate
OK database created.

enter browser => http://localhost/yii2shop/frontend/web/

Error show ....

Invalid Parameter – yii\base\InvalidParamException
The file or directory to be published does not exist: C:\xampp\htdocs\yii2shop/vendor\bower/jquery/dist

**Comment by songwutk** [comment]
My Solution is clone master yii2 advanced and copy your project overwrite yii2 advanced.

**Comment by samdark** [comment]
Done.
