### ISSUE TITLE
Should Use Environments To Setup Config

### ISSUE THREAD

**Issue by CyberPunkCodes** [samdark/yii2-shop#26]
Hey, in my opinion, they should use the `environments` directory for setting up config settings. I am not sure exactly what changes you have compared to default Yii2 Advanced.

If they `init` first, then modify `/common/config/main-local.php` to include their db info, it will be overwritten next time they run init.

They should first modify `/environments/dev/common/config/main-local.php` and get it they way they want for development (db info, etc). Then run `init`. This way, they don't lose any of their settings.

**Comment by samdark** [comment]
init is, in general, either executed once per server or executed with ignoring local changes.
