### ISSUE TITLE
Interface 'yz\shoppingcart\CartPositionInterface' not found

### ISSUE THREAD

**Issue by echojust** [samdark/yii2-shop#27]
Hi! I am learning the YII2.And I am very glad to learn by your code.but when i run it,it throw a Fatal Error.
`PHP Fatal Error – yii\base\ErrorException

Interface 'yz\shoppingcart\CartPositionInterface' not found`

I found that no yz folder.How can i get it??Thanks

**Comment by samdark** [comment]
Run `composer install` where `composer.json` is.
