### ISSUE TITLE
Не хватает компонентов

### ISSUE THREAD

**Issue by asyou99** [samdark/yii2-shop#28]
Здравствуйте.

Занялся изучением yii2 и для примера изучаю как построен ваш мини-магазин, но при его установке возникло пару проблем возможно Вы поможете их решить:
1. В описании есть папке вендоров в репозитории ее нету (закинул стандартную папку с эдвансета версии 2.0.9)
2. Бекэнд запустился, а вот во фронтэнде пишет что нет таких путей:
   use yz\shoppingcart\CartPositionInterface;
   use yz\shoppingcart\CartPositionTrait;

Подскажите где достать недостающие файлы что бы приложение запустилось?

**Comment by samdark** [comment]
Не надо закидывать. Надо [как в README написано](https://github.com/samdark/yii2-shop/blob/master/README.md#install-via-composer). При помощи composer.

**Comment by asyou99** [comment]
Понятно спасибо.
Но теперь композер выдает ошибки по пакетам.
На сколько понимаю проект был заточен под версию 2.0.3 с сответсвующими
зависимостями а время прошло и все поменялось. ок сенкс буду долбить
компосер.

  Problem 1
    - Installation request for yiisoft/yii2-composer 2.0.3 -> satisfiable
by yiisoft/yii2-composer[2.0.3].
    - yiisoft/yii2-composer 2.0.3 requires composer-plugin-api 1.0.0 -> no
matching package found.
  Problem 2
    - yiisoft/yii2-composer 2.0.3 requires composer-plugin-api 1.0.0 -> no
matching package found.
    - yiisoft/yii2 2.0.3 requires yiisoft/yii2-composer \* -> satisfiable by
yiisoft/yii2-composer[2.0.3].
    - Installation request for yiisoft/yii2 2.0.3 -> satisfiable by
yiisoft/yii2[2.0.3].

2016-08-16 1:54 GMT+03:00 Alexander Makarov notifications@github.com:

**Comment by samdark** [comment]
Можно сделать composer update.

**Comment by asyou99** [comment]
Не апдейт тоже не помогает. Спасибо буду бороться с зависимостями.
