### ISSUE TITLE
How Signup to admin

### ISSUE THREAD

**Issue by mohammad1381** [samdark/yii2-shop#29]
How Signup to admin? there is no signup link.

**Comment by samdark** [comment]
site/login

**Comment by mohammad1381** [comment]
Link for signup not fro login.
Give me full address, for example for login to backend: http://localhost/yii2-shop/backend/index.php?r=site%2Flogin

**Comment by samdark** [comment]
Yes, it's not there. Feel free to send a pull request adding it.

**Comment by mohammad1381** [comment]
Excuse me I non't know English well. I did't get you mean.
 What I have to do now?

**Comment by samdark** [comment]
You can send a [pull request](https://help.github.com/articles/creating-a-pull-request/) if you want to fix it.

**Comment by mohammad1381** [comment]
I don't need it any more now, maybe later. thanks a lot.

**Comment by mohammad1381** [comment]
I don't need it any more now, maybe later. thanks a lot.
