### ISSUE TITLE
How can I add discount for prices?

### ISSUE THREAD

**Issue by mohammad1381** [samdark/yii2-shop#30]
I want to add discount for some stuff. There is a function for this or not?
How can I do it?

**Comment by samdark** [comment]
No, there's no function for that in this code.

**Comment by mohammad1381** [comment]
Could you please add function for this?

**Comment by samdark** [comment]
No. It was one time example project for a workshop. I'm not maintaining the code. If you are willing to take over, I can give you permissions for the repository.

**Comment by mohammad1381** [comment]
Thanks a lot. I made it by myself now. It works perfectly.
