### ISSUE TITLE
Problem installing script

### ISSUE THREAD

**Issue by ckAutoKartz** [samdark/yii2-shop#33]
Hello,

I am trying to install the package as the given instruction. But when I issue "Composer Install" I get the following errors. I am totally new to Yii and need help. 
Error : 
E:\xampp\htdocs\yii2-shop (master)
λ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yiisoft/yii2-composer 2.0.3 -> satisfiable by yiisoft/yii2-composer[2.0.3].
    - yiisoft/yii2-composer 2.0.3 requires composer-plugin-api 1.0.0 -> no matching package found.
  Problem 2
    - yiisoft/yii2-composer 2.0.3 requires composer-plugin-api 1.0.0 -> no matching package found.
    - yiisoft/yii2 2.0.3 requires yiisoft/yii2-composer * -> satisfiable by yiisoft/yii2-composer[2.0.3].
    - Installation request for yiisoft/yii2 2.0.3 -> satisfiable by yiisoft/yii2[2.0.3].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

**Comment by samdark** [comment]
http://www.yiiframework.com/doc-2.0/guide-start-installation.html
