### ISSUE TITLE
ShoppingCart::getCount() Error

### ISSUE THREAD

**Issue by Slick335** [samdark/yii2-shop#4]
Hey, I just wanted to take a look at this shop beacause I'm learning yii2 at the moment, but I always get an error. No files edited though.

yz\shoppingcart\ShoppingCart::getCount(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;common\models\Article&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition

**Comment by samdark** [comment]
How to reproduce it?

**Comment by Slick335** [comment]
Owh, seems that the problem occurs when there's two applications running at the same time in the same browser. At least it seems so on my system.

**Comment by samdark** [comment]
Same domain?

**Comment by Slick335** [comment]
XAMPP's localhost, but of course separated directories. So the actual paths are different.

**Comment by samdark** [comment]
The issue is that cookies by default are set for root path. Yii websites are meant to be hosted on separate domains by default. You can adjust cookie path, of course.
