### ISSUE TITLE
 If the root category is added last, its value may not be displayed

### ISSUE THREAD

**Issue by leyestd** [samdark/yii2-shop#5]
CatalogController.php

``` php
 foreach ($categories as $category) {
      if ($category->parent_id === null) {
            $menuItems[$category->id] = [
             'active' => $activeId === $category->id,
             'label' => $category->title,
          'url' => ['catalog/list', 'id' => $category->id],
      ];
     } else {
         $this->placeCategory($category, $menuItems, $activeId);
     }
}
```

If the root category is added last, its value may not be displayed

**Comment by samdark** [comment]
Why?

**Comment by leyestd** [comment]
category
When the parent ID is greater than the subclass ID, what can go wrong

**Comment by samdark** [comment]
But there's no way to add root category after adding subcategories. Are there?

**Comment by leyestd** [comment]
If not add, but changed it

**Comment by samdark** [comment]
Changed it in database or using UI?

**Comment by leyestd** [comment]
backend crud ui

**Comment by leyestd** [comment]
ID  Parent  Title
2   -   野生  
4   -   花 
6   -   月朋  
1   野生  家养

fontend only diplay
    野生
    花
    月朋
