### ISSUE TITLE
How can I install yii2-shop

### ISSUE THREAD

**Issue by fabiomlferreira** [samdark/yii2-shop#6]
In installation notes you have this commands:
composer global require "fxp/composer-asset-plugin:1.0.0"
composer install

This commands don't install yii2-shop, how can we install the template using composer?

**Comment by samdark** [comment]
You need to clone repo with git before running composer install.

**Comment by sbfnxk201** [comment]
where i can find yz\shoppingcart\CartPositionInterface  class file.
Interface 'yz\shoppingcart\CartPositionInterface' not found
